"""car media

Revision ID: 3e3a939f2699
Revises: 914b5d25eb4e
Create Date: 2026-03-03 13:13:47.548159
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '3e3a939f2699'
down_revision: Union[str, Sequence[str], None] = '914b5d25eb4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
