"""add leads

Revision ID: 84d1654a1402
Revises: 5c7b0c3f2e41
Create Date: 2026-03-07 13:10:06.468983
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '84d1654a1402'
down_revision: Union[str, Sequence[str], None] = '5c7b0c3f2e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
